language: ruby

dist: xenial

rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - ruby-head

addons:
  firefox: latest

branches:
  only:
    - master

services:
  - xvfb

gemfile:
  - gemfiles/rails_6_0.gemfile
  - gemfiles/rails_5_2.gemfile
  - gemfiles/rails_5_1.gemfile
  - gemfiles/rails_5_0.gemfile
  - gemfiles/rails_4_2.gemfile

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
  exclude:
  # Only test Rails6 on supported rubies
  # Don't test lowest rails support on maintained rubies
    - rvm: 2.3
      gemfile: gemfiles/rails_6_0.gemfile
    - rvm: 2.4
      gemfile: gemfiles/rails_4_2.gemfile
    - rvm: 2.4
      gemfile: gemfiles/rails_6_0.gemfile
    - rvm: 2.5
      gemfile: gemfiles/rails_4_2.gemfile
    - rvm: 2.6
      gemfile: gemfiles/rails_4_2.gemfile
    - rvm: 2.6
      gemfile: gemfiles/rails_5_0.gemfile
    - rvm: 2.6
      gemfile: gemfiles/rails_5_1.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails_4_2.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails_5_0.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails_5_1.gemfile

before_install:
  - gem install --remote bundler -v '~> 1.17'
  - bin/install_geckodriver.sh
  - bin/install_webpacker.sh
